Add ktvalidate alias to validate kube templates

diff --git a/ad_profile b/ad_profile
--- a/ad_profile
+++ b/ad_profile
@@ -15,6 +15,22 @@ open_pull_request() {
     hub pull-request --copy $prusers
 }
 
+kube_templator_validate() {
+    if [ ! -z $1 ]; then
+        logLevel="$1"
+    else
+        logLevel="ERROR"
+    fi
+    docker run --rm -v $(pwd):/tmp -v "$HOME/.config/hub":/app/hub -e LOG_LEVEL=$logLevel docker.appdirect.tools/kube-templator/validate:latest
+    rc=$?
+    if [[ $rc != 0 ]]; then 
+        echo "Execution error!"
+    else
+        echo "Success!"
+    fi
+}
+
+alias ktvalidate="kube_templator_validate"
 alias openpr="open_pull_request"
 alias vpnstart="sudo openconnect -b --authgroup=Duo --user=leo.almeida iceman.appdirect.com"
 alias vpnstartbatman="sudo openconnect -b --authgroup=Duo --user=leo.almeida batman.appdirect.com"
